export const PROMPTS = [
  "Name something you'd find in a wizard's pocket",
  "Name a reason someone would leave their own party early",
  "Name something you shouldn't say on a first date",
  "Name a superpower that sounds useful but actually isn't",
  "Name something you'd find in a time traveler's backpack",
  "Name a job title that doesn't exist but should",
  "Name something a villain would put on their dating profile",
  "Name a bad ice cream flavor that would sell anyway",
  "Name a sign that your dog might actually be a spy",
  "Name something that sounds illegal but isn't",
  "Name something you'd find in Dracula's fridge",
  "Name a feature every phone should have but doesn't",
  "Name something you'd say to an alien instead of 'hello'",
  "Name a bad supervillain weakness",
  "Name a surprising career change for Santa Claus",
  "Name something worse than stepping on a LEGO",
  "Name a red flag in a restaurant",
  "Name something a ghost would complain about",
  "Name a bad WiFi password",
  "Name something you shouldn't bring to a funeral",
  "Name a job that robots will never replace",
  "Name something that should have a warning label but doesn't",
  "Name a disappointing thing to find at the end of a rainbow",
  "Name something that gets better with age (but probably shouldn't)",
  "Name a terrible reason to call 911",
  "Name a reason to walk out of a restaurant after 5 minutes",
  "Name something you'd barter with in a post-apocalypse",
  "Name a bad name for a therapist",
  "Name something you shouldn't Google at work",
  "Name a terrible band name that somehow already exists",
];
